[package]
name = "leptos-tutorial"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.13.0"
leptos = { version = "0.6.15", features = ["csr", "serde"] }
serde = "1.0.213"
serde_json = "1.0.132"
web-sys = { version = "0.3.72", features = ["Storage"] }
